name: Build and Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]  # This will trigger on tags starting with 'v'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Make build.sh executable
      run: chmod +x ./build.sh

    - name: Run build script
      run: ./build.sh

    - name: Check if output files exist
      id: check_files
      run: |
        FILES=(
          "./openwrt/bin/targets/econet/en751221/openwrt-econet-en751221-smartfiber_xp8421-b-squashfs-tclinux.trx"
          "./openwrt/bin/targets/econet/en751221/openwrt-econet-en751221-tplink_archer-vr1200v-v2-squashfs-sysupgrade.bin"
          "./openwrt/bin/targets/econet/en751221/openwrt-econet-en751221-nokia_g240g-e-squashfs-tclinux.trx"
          "./openwrt/bin/targets/econet/en751221/openwrt-econet-en751221-en751221_generic-initramfs-kernel.bin"
          "./openwrt/bin/targets/econet/en751221/openwrt-econet-en751221-zyxel_pmg5617ga-squashfs-tclinux.trx"
        )
        ALL_EXIST=true
        for FILE in "${FILES[@]}"; do
          if [ -f "$FILE" ]; then
            echo "$FILE exists"
          else
            echo "$FILE does not exist"
            ALL_EXIST=false
          fi
        done
        if [ "$ALL_EXIST" = "true" ]; then
          echo "All files exist"
          echo "files_exist=true" >> $GITHUB_OUTPUT
        else
          echo "One or more files missing"
          echo "files_exist=false" >> $GITHUB_OUTPUT
          exit 1
        fi

    - name: Create Release and Upload Assets
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && steps.check_files.outputs.files_exist == 'true'
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ./openwrt/bin/targets/econet/en751221/openwrt-econet-en751221-smartfiber_xp8421-b-squashfs-tclinux.trx
          ./openwrt/bin/targets/econet/en751221/openwrt-econet-en751221-tplink_archer-vr1200v-v2-squashfs-sysupgrade.bin
          ./openwrt/bin/targets/econet/en751221/openwrt-econet-en751221-nokia_g240g-e-squashfs-tclinux.trx
          ./openwrt/bin/targets/econet/en751221/openwrt-econet-en751221-en751221_generic-initramfs-kernel.bin
          ./openwrt/bin/targets/econet/en751221/openwrt-econet-en751221-zyxel_pmg5617ga-squashfs-tclinux.trx
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
